name: galonku
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^4.8.1
  english_words: ^4.0.0
  faker: ^2.1.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.0.0
  flutter_facebook_auth: ^6.0.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  geolocator: ^7.7.0
  google_maps: ^6.3.0
  google_maps_flutter: ^2.2.8
  google_sign_in: ^6.1.4
  image_picker: ^0.8.4+3
  provider: ^6.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.10

dev_dependencies:
  flutter_barcode_scanner: ^2.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.12

flutter:
  uses-material-design: true
  assets:
    - images/page_1.png
    - images/page_2.png
    - images/page_3.png
    - images/role.png
    - images/Sinkronisasi_facebook.png
    - images/Sinkronisasi_google.png
    - images/google_logo.png
    - images/facebook_logo.png
    - images/atau.png
    - images/Icon_HomePage.png
    - images/Icon_Maps.png
    - images/Icon_Pesan.png
    - images/Icon_Pesanan.png
    - images/Icon_Setting.png
    - images/Depot_Uang.png
    - images/grafik_profit.png
    - images/rata_pendapatan.png
    - images/arrow_profit.png
    - images/test_foto.png
    - images/piala.png
    - images/galon.png
    - images/promo.png
    - images/Rating.png
    - images/logo_chat.png
